### ISSUE TITLE
Room Class

### ISSUE THREAD

**Issue by mattpadgett** [Tervoc/roomee-api#3]
Issues with the Room.cs class:

- Why does this class have a ToClaims function? What is the use of a Claim to a list of claims? Explain, please.

That's the only one currently. May add more as you make more progress here.

**Comment by Tervoc** [comment]
The use of claims in this context is for the data a Json Web Token is claiming to store and the list of claims is the list of claims a JWT is claiming to store. 
This class has a ToClaims function because the User class was used as its framework and the ToClaims function was incorrectly kept in the class structure. The Room class has no need for claims because it has no need for tokens.

**Comment by mattpadgett** [comment]
Ah, no worries. Could you please remove and create a PR?
